cls
REM python osearch.py "Lit_Ms_E_41 065r.jpg" -f "065" "you"
REM python osearch.py "Lit_Ms_E_41 066 (2)r.jpg" -f "066_2" "you"
REM python osearch.py "Lit_Ms_E_41 066r.jpg" -f "066" "you"
REM python osearch.py "Lit_Ms_E_41 067 (2)r.jpg" -f "067_2" "you"
REM python osearch.py "Lit_Ms_E_41 067r.jpg" -f "067" "you"
REM python osearch.py "Lit_Ms_E_41 068 (2)r.jpg" -f "068_2" "you"
REM python osearch.py "Lit_Ms_E_41 068r.jpg" -f "068" "you"
REM python osearch.py "Lit_Ms_E_41 069 (2)r.jpg" -f "069_2" "you"
REM python osearch.py "Lit_Ms_E_41 069r.jpg" -f "069" "you"
python osearch.py "Lit_Ms_E_41 070 (2)r.jpg" -f "070_2" "y"
python osearch.py "Lit_Ms_E_41 070r.jpg" -f "070" "y"
python osearch.py "Lit_Ms_E_41 071 (2)r.jpg" -f "071_2" "you"
REM python osearch.py "Lit_Ms_E_41 071r.jpg" -f "071" "you"
REM python osearch.py "Lit_Ms_E_41 072 (2)r.jpg" -f "072_2" "you"
REM python osearch.py "Lit_Ms_E_41 072r.jpg" -f "072" "you"
REM python osearch.py "Lit_Ms_E_41 073 (2)r.jpg" -f "073_2" "you"
REM python osearch.py "Lit_Ms_E_41 073r.jpg" -f "073" "you"
REM python osearch.py "Lit_Ms_E_41 074 (2)r.jpg" -f "074_2" "you"
python osearch.py "Lit_Ms_E_41 074r.jpg" -f "074" "you"
python osearch.py "Lit_Ms_E_41 075 (2)r.jpg" -f "075_2" "you"

REM python osearch.py "testimage.jpg" -f "070" "you"
REM python osearch.py "test2.jpg" -f "070" "you"

REM python osearch.py "Lit_Ms_E_41 070r.jpg" -s "Q. Ordinance? what’s that? a Gun? If it be, he’s no such strong\npiece of mans flesh. I haue known him sett in the stocks ere\nnow.\nS Indeed, Iron, I think this is but a meer crack of yours. You’ll\novershoot yourselves presently, but I’ll teach you to chamber your\ntongs. I. Nay I am the man for tongs.\nG. Tis true, Iron, you are a double tongued slave. But I hope your\npair of tongs shall never carry away the cause, if you goe to plead\nit once\nQ. Why I hope you will grant that Iron is excellent at the Barr\nG. I grant that. Yet I think he is but a poor Lawyer. He can make\na bill indeed, but it is alwaies forged\nQ. If it be forg’d, I am sure gold is coin’d. Aside.\nG. I am the man must doe the deed. I know the Lawyer will doe\nmore for Gold, then for any of you all. They loue me soe they’ll\ndoe nothing without mee\nS. It may be then, Gold, you think to prevail at the Common law,\nbut I’ll haue you into the Exchequer\nQ. Indeed that’s hard to doe. But Silver hath met with you there,\nGold. What sayest to this? not a word? I think thou art quite\nspent, Gold.\nG If I be put into the Exchequer, I am sure to be deliver’d. There\nbe Courtiers enow to help me out, and Ladyes too, and You also,\nSilver, for a need.\nL Gold is in sometimes upon occasion, and other times out upon\nuse, if the Officers can get the Souldiers to stay for their pay.\nAnd yet I think there are as many would keep you in, as lett you out\nBut let’s pass from this lawcase. For I think you all talk, and talk, &amp;\nknow not the Law. Let’s try our worth by force of arms.\nG I am content. You shall see what arms I bear. Offers to strike\nB Nay, good Gentlemen, be quiet, I pray. I poor Brass shall sound\npresently, if you fall to striking.\nQ. What durst you not buckle, Brass,? Fly Brass, fly, If you be\nsuch a coward: if you loue your ease, begone\nB. Well, call me coward, I care not, so I haue not the cowards blow.\nS. Come, Gold, a ring with you" "king"

REM python getBoxes.py "Lit_Ms_E_41 070r.jpg"